version: '3'
services:
  lol:
    build: env
    hostname: common-lisp
    container_name: dev
    volumes:
      - ./src:/app
    working_dir: /app
    ports: 
      - 8888:8888
    expose: 
      - 8888
    
